# English (United Kingdom) translations for oslo.concurrency.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the oslo.concurrency
# project.
#
# Translators:
# Andi Chandler <andi@gowling.com>, 2014-2015
msgid ""
msgstr ""
"Project-Id-Version:  oslo.concurrency\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-24 06:04+0000\n"
"PO-Revision-Date: 2015-03-24 01:19+0000\n"
"Last-Translator: Andi Chandler <andi@gowling.com>\n"
"Language-Team: English (United Kingdom) "
"(http://www.transifex.com/projects/p/osloconcurrency/language/en_GB/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: oslo_concurrency/lockutils.py:125
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr "Unable to acquire lock on `%(filename)s` due to %(exception)s"

#: oslo_concurrency/lockutils.py:222
msgid "Unable to release an unacquired lock"
msgstr "Unable to release an unacquired lock"

#: oslo_concurrency/lockutils.py:685
msgid ""
"Calling lockutils directly is no longer supported.  Please use the "
"lockutils-wrapper console script instead."
msgstr ""
"Calling lockutils directly is no longer supported.  Please use the "
"lockutils-wrapper console script instead."

#: oslo_concurrency/processutils.py:69
msgid "Unexpected error while running command."
msgstr "Unexpected error while running command."

#: oslo_concurrency/processutils.py:72
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:174
#, python-format
msgid "Got unknown keyword args: %r"
msgstr "Got unknown keyword args: %r"

#: oslo_concurrency/processutils.py:177
#, python-format
msgid "Got invalid arg log_errors: %r"
msgstr "Got invalid arg log_errors: %r"

#: oslo_concurrency/processutils.py:183
msgid "Command requested root, but did not specify a root helper."
msgstr "Command requested root, but did not specify a root helper."

#: oslo_concurrency/processutils.py:199
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr "Running cmd (subprocess): %s"

#: oslo_concurrency/processutils.py:242
#, python-format
msgid ""
"%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"
msgstr ""
"%(desc)r\n"
"command: %(cmd)r\n"
"exit code: %(code)r\n"
"stdout: %(stdout)r\n"
"stderr: %(stderr)r"

#: oslo_concurrency/processutils.py:251
#, python-format
msgid ""
"Got an OSError\n"
"command: %(cmd)r\n"
"errno: %(errno)r"
msgstr ""
"Got an OSError\n"
"command: %(cmd)r\n"
"errno: %(errno)r"

#: oslo_concurrency/processutils.py:257
#, python-format
msgid "%r failed. Not Retrying."
msgstr "%r failed. Not Retrying."

#: oslo_concurrency/processutils.py:261
#, python-format
msgid "%r failed. Retrying."
msgstr "%r failed. Retrying."

#: oslo_concurrency/processutils.py:308
msgid "Environment not supported over SSH"
msgstr "Environment not supported over SSH"

#: oslo_concurrency/processutils.py:312
msgid "process_input not supported over SSH"
msgstr "process_input not supported over SSH"

